sudo: false
language: python
env:
      global:
        # Doctr deploy key for ARM-DOE/ACT
        - secure: "hT9zNd40Rn45cDKKMiucnwDAjdXQJm86zWgr0fBV7mwe+kqHYk94NVtD5X6khkwkNSisYz+x9R4bK5eQV1o54S1rwhNDNIfLqMDW6lrtGEw/2YFXDKnzUYpWTx7zGa9agEZM7IM6UjYdDWa2E1KMq42rVTWUGuhQuYtA8vfAPUjAIRzJ8YvvVedlsnFHYnecGlszNiWTI+z/SIL0O6iGOlhXto4wbC+PpFiOoR8wAQSe+YqjjJxm4mmd13oIg6pxNEbIXx14BxlVnyS2FvpBJ3oMVuNrp2yk2EYew2s6gEfrGPxxrxpQnK8ugZGtsYmmMx9u5NRB140VIL3+kN82WuWn9NPPb4696I+nulmXpNxLQ6/J9E9DPQoRVb5OzT5DAyCnK0nU5jOxdqrTwP/FDc9uLZceyEYOnSF3bIcdu8oadkjspnu8h0vDOv2Zn1T2ViToNFvgLbkxm9IvgdgjwXmsyOrNRBCv9a73sHg3Y9XYvoz163QnyLTIXicYiPirreYQL/uHkRkqfaIEXB6ejtwPsr7fW0KXjSOCxkC9/NKFJa1LbFaw7NM+RBxUIi9Ic8dpgNbhedSXxDLuUYzlG4crZP8JacH58lzcyP5cUSlnLjcZ9WqTwg5Dbt2KV4bxMSUeRA3SybSbo3ojkHvtDTvjLCefHpjEFxaXzupkDvw="


matrix:
    include:
    - python: 3.7
      env:
        - PYTHON_VERSION="3.7"
        - DOC_BUILD="true"     
    - python: 3.8
      sudo: yes
      dist: xenial
      env:
        - PYTHON_VERSION="3.8"
        - DOC_BUILD="true"
install:
    - source continuous_integration/install.sh
    - pip install pytest-cov
    - pip install coveralls
script:
    - eval xvfb-run pytest --mpl --cov=act/ --cov-config=.coveragerc
    - flake8 --max-line-length=115 --ignore=F401,E402,W504,W605,F403
after_success:
    - coveralls
    - source continuous_integration/build_docs.sh;
