# Basic environment for ACT.
name: act_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - xarray
  - matplotlib
  - dask
  - distributed
  - pandas
  - pint
  - requests
  - pyproj>=2.0.0
  - pip
  - astral
