# Basic environment for ACT.
name: act_env
channels:
  - conda-forge
dependencies:
  - cartopy
  - pyproj
  - matplotlib>=3.7
  - numpy
  - scipy
  - netcdf4
  - dask
  - xarray
  - ipython
  - skyfield
  - lxml
  - scikit-posthocs
  - flake8
  - pytest
  - pytest-cov
  - pytest-mpl
  - coveralls
  - pandas
  - shapely
  - lazy_loader
  - cmweather
  - moviepy
  - ruff
  - pip
  - pip:
    - mpl2nc
    - metpy
    - pysp2
    - arm_pyart
    - icartt
    - aiohttp>=3.9.0b1
    - git+https://github.com/ARM-DOE/arm-test-data.git
