# Basic environment for ACT.
name: act_env
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - pyproj
  - matplotlib>=3.7
  - numpy
  - scipy
  - netcdf4
  - dask
  - xarray
  - ipython
  - pint=0.8.1
  - skyfield
  - lxml
  - scikit-posthocs
  - flake8
  - pytest
  - pytest-cov
  - pytest-mpl
  - coveralls
  - pandas
  - shapely
  - lazy_loader
  - cmweather
  - arm-test-data
  - moviepy
  - ruff
  - pip
  - pip:
    - mpl2nc
    - metpy
    - pysp2
    - arm_pyart
    - icartt
    - aiohttp>=3.9.0b1
