name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cartopy
  - pyproj
  - numpy
  - scipy
  - matplotlib<=3.2.2
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - dask
  - xarray
  - flake8
  - ipython
  - pint=0.8.1
  - pip
  - pip:
    - mpl2nc
    - arm-pyart
    - astral>=2.2
