name: act-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - pyproj
  - numpy
  - scipy
  - matplotlib>=3.5.1
  - netcdf4
  - dask
  - xarray
  - ipython
  - notebook
  - pint=0.8.1
  - skyfield
  - scikit-posthocs
  - pip
  - shapely<1.8.3
  - arm-test-data
  - moviepy
  - pip:
    - mpl2nc
    - lazy_loader
    - metpy>=1.2
    - arm-pyart
    - sphinx
    - sphinx_gallery
    - sphinx-copybutton
    - pydata-sphinx-theme
    - myst_nb
    - ablog
    - sphinx_design
    - nbsphinx
    - pooch
    - icartt
    - cmweather
    - sphinxcontrib-devhelp==1.0.5
    - sphinxcontrib-htmlhelp==2.0.4
    - sphinxcontrib-qthelp==1.0.6
    - sphinxcontrib-serializinghtml==1.1.9
